---
version: '3'

services:
  apache2-perl-cgi:
    container_name: apache2-perl-cgi
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/apache2-perl-cgi:latest
    ports:
      - 80:80
    volumes:
      - ${PWD}/cgi-bin:/usr/lib/cgi-bin
    working_dir: /etc/apache2
    entrypoint:
      - /usr/sbin/apachectl
    command:
      - -D
      - FOREGROUND
